version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: research_assistant_db
    environment:
      POSTGRES_DB: research_assistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: research_assistant_web
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 --timeout 120 app:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - DEBUG=False
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=research_assistant
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SECRET_KEY=change-this-in-production
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: